[webservers]
web-1 ansible_host=10.10.110.22 ansible_user=ubuntu
web-2 ansible_host=10.10.120.28 ansible_user=ubuntu

[bastion_hosts]
bastion ansible_host=81.26.177.166 ansible_user=ubuntu

[webservers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p ubuntu@81.26.177.166" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
