
[webservers]
web-a ansible_host=10.130.0.16 ansible_user=ubuntu
web-b ansible_host=10.130.0.11 ansible_user=ubuntu

[bastion]
bastion ansible_host=ВАШ_ВНЕШНИЙ_IP_БАСТИОНА ansible_user=ubuntu

[webservers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@В
